package repository

import "LocationLunatics/internal/models"

func GetAllLocationData() []models.Location {
	return []models.Location{
		{
			Name:                 "Location 1",
			PMZoneCode:           "108045",
			Lat:                  -84.377881,
			Long:                 33.839611,
			MainStreet:           "Milk Street",
			CrossStreet:          "Soda Ave",
			CrossStreetTwo:       "Water Boulevard",
			SpaceCount:           "100",
			MeterType:            "MSM",
			RateName:             "Business",
			EnforcementType:      "Pay by plate",
			HourlyRate:           "$2.00",
			MaxDurationInMinutes: "180",
			MinimumAmount:        "30",
			IncrementsInMinutes:  "30",
			ZoneGroupID:          2,
		},
		{
			Name:                 "Location 2",
			PMZoneCode:           "108067",
			Lat:                  -84.380220,
			Long:                 33.782563,
			MainStreet:           "Shoes Street",
			CrossStreet:          "Pants Ave",
			CrossStreetTwo:       "Shirt Boulevard",
			SpaceCount:           "100",
			MeterType:            "MSM",
			RateName:             "Business",
			EnforcementType:      "Pay by plate",
			HourlyRate:           "$2.00",
			MaxDurationInMinutes: "180",
			MinimumAmount:        "30",
			IncrementsInMinutes:  "30",
			ZoneGroupID:          2,
		},
		{
			Name:                 "Location 3",
			PMZoneCode:           "404101",
			Lat:                  -84.387803,
			Long:                 33.748822,
			MainStreet:           "Truck Street",
			CrossStreet:          "Bike Ave",
			CrossStreetTwo:       "Car Boulevard",
			SpaceCount:           "100",
			MeterType:            "MSM",
			RateName:             "Business",
			EnforcementType:      "Pay by plate",
			HourlyRate:           "$2.00",
			MaxDurationInMinutes: "180",
			MinimumAmount:        "30",
			IncrementsInMinutes:  "30",
			ZoneGroupID:          2,
		},
		{
			Name:                 "Location 4",
			PMZoneCode:           "714014",
			Lat:                  -84.388214,
			Long:                 33.747991,
			MainStreet:           "Jupiter Street",
			CrossStreet:          "Mars Ave",
			CrossStreetTwo:       "Saturn Boulevard",
			SpaceCount:           "100",
			MeterType:            "MSM",
			RateName:             "Business",
			EnforcementType:      "Pay by plate",
			HourlyRate:           "$2.00",
			MaxDurationInMinutes: "180",
			MinimumAmount:        "30",
			IncrementsInMinutes:  "30",
			ZoneGroupID:          2,
		},
		{
			Name:                 "Location 5",
			PMZoneCode:           "714015",
			Lat:                  -84.387221,
			Long:                 33.748861,
			MainStreet:           "Dog Street",
			CrossStreet:          "Cat Ave",
			CrossStreetTwo:       "Horse Boulevard",
			SpaceCount:           "100",
			MeterType:            "MSM",
			RateName:             "Business",
			EnforcementType:      "Pay by plate",
			HourlyRate:           "$2.00",
			MaxDurationInMinutes: "180",
			MinimumAmount:        "30",
			IncrementsInMinutes:  "30",
			ZoneGroupID:          2,
		},
		{
			Name:                 "Location 6",
			PMZoneCode:           "714017",
			Lat:                  -84.388993,
			Long:                 33.748901,
			MainStreet:           "Tree Street",
			CrossStreet:          "Plant Ave",
			CrossStreetTwo:       "Leaf Boulevard",
			SpaceCount:           "100",
			MeterType:            "MSM",
			RateName:             "Business",
			EnforcementType:      "Pay by plate",
			HourlyRate:           "$2.00",
			MaxDurationInMinutes: "180",
			MinimumAmount:        "30",
			IncrementsInMinutes:  "30",
			ZoneGroupID:          2,
		},
		{
			Name:                 "Location 7",
			PMZoneCode:           "714018",
			Lat:                  -84.388621,
			Long:                 33.748955,
			MainStreet:           "Middle Ground Street",
			CrossStreet:          "Real Ave",
			CrossStreetTwo:       "Fake Boulevard",
			SpaceCount:           "100",
			MeterType:            "MSM",
			RateName:             "Business",
			EnforcementType:      "Pay by plate",
			HourlyRate:           "$2.00",
			MaxDurationInMinutes: "180",
			MinimumAmount:        "30",
			IncrementsInMinutes:  "30",
			ZoneGroupID:          2,
		},
		{
			Name:                 "Location 8",
			PMZoneCode:           "714019",
			Lat:                  -84.388582,
			Long:                 33.749042,
			MainStreet:           "Place Street",
			CrossStreet:          "Boulevard Ave",
			CrossStreetTwo:       "Avenue Boulevard",
			SpaceCount:           "100",
			MeterType:            "MSM",
			RateName:             "Business",
			EnforcementType:      "Pay by plate",
			HourlyRate:           "$2.00",
			MaxDurationInMinutes: "180",
			MinimumAmount:        "30",
			IncrementsInMinutes:  "30",
			ZoneGroupID:          2,
		},
		{
			Name:                 "Location 9",
			PMZoneCode:           "714036",
			Lat:                  -84.389075,
			Long:                 33.790205,
			MainStreet:           "Visible Street",
			CrossStreet:          "Noticeable Ave",
			CrossStreetTwo:       "Unique Boulevard",
			SpaceCount:           "100",
			MeterType:            "MSM",
			RateName:             "Business",
			EnforcementType:      "Pay by plate",
			HourlyRate:           "$2.00",
			MaxDurationInMinutes: "180",
			MinimumAmount:        "30",
			IncrementsInMinutes:  "30",
			ZoneGroupID:          2,
		},
		{
			Name:                 "Location 10",
			PMZoneCode:           "714051",
			Lat:                  -84.388011,
			Long:                 33.749214,
			MainStreet:           "Street Street",
			CrossStreet:          "Location Zone",
			CrossStreetTwo:       "Line Lane",
			SpaceCount:           "100",
			MeterType:            "MSM",
			RateName:             "Business",
			EnforcementType:      "Pay by plate",
			HourlyRate:           "$2.00",
			MaxDurationInMinutes: "180",
			MinimumAmount:        "30",
			IncrementsInMinutes:  "30",
			ZoneGroupID:          2,
		},
		{
			Name:                 "Location 11",
			PMZoneCode:           "714055",
			Lat:                  -84.383177,
			Long:                 33.776766,
			MainStreet:           "Boulevard Street",
			CrossStreet:          "Road Ave",
			CrossStreetTwo:       "Hypothetical Boulevard",
			SpaceCount:           "100",
			MeterType:            "MSM",
			RateName:             "Business",
			EnforcementType:      "Pay by plate",
			HourlyRate:           "$2.00",
			MaxDurationInMinutes: "180",
			MinimumAmount:        "30",
			IncrementsInMinutes:  "30",
			ZoneGroupID:          2,
		},
		{
			Name:                 "Location 12",
			PMZoneCode:           "714057",
			Lat:                  -84.388011,
			Long:                 33.749214,
			MainStreet:           "Back Road",
			CrossStreet:          "Location Ave",
			CrossStreetTwo:       "Place Boulevard",
			SpaceCount:           "100",
			MeterType:            "MSM",
			RateName:             "Business",
			EnforcementType:      "Pay by plate",
			HourlyRate:           "$2.00",
			MaxDurationInMinutes: "180",
			MinimumAmount:        "30",
			IncrementsInMinutes:  "30",
			ZoneGroupID:          2,
		},
		{
			Name:                 "Location 13",
			PMZoneCode:           "714070",
			Lat:                  -84.387803,
			Long:                 33.748822,
			MainStreet:           "No Way Street",
			CrossStreet:          "Avenue Ave",
			CrossStreetTwo:       "Blvd Boulevard",
			SpaceCount:           "100",
			MeterType:            "MSM",
			RateName:             "Business",
			EnforcementType:      "Pay by plate",
			HourlyRate:           "$2.00",
			MaxDurationInMinutes: "180",
			MinimumAmount:        "30",
			IncrementsInMinutes:  "30",
			ZoneGroupID:          3,
		},
		{
			Name:                 "Location 14",
			PMZoneCode:           "714086",
			Lat:                  -84.387803,
			Long:                 33.748822,
			MainStreet:           "Existing Street",
			CrossStreet:          "Imaginary Ave",
			CrossStreetTwo:       "Fake Boulevard",
			SpaceCount:           "100",
			MeterType:            "MSM",
			RateName:             "Business",
			EnforcementType:      "Pay by plate",
			HourlyRate:           "$2.00",
			MaxDurationInMinutes: "180",
			MinimumAmount:        "30",
			IncrementsInMinutes:  "30",
			ZoneGroupID:          3,
		},
		{
			Name:                 "Location 15",
			PMZoneCode:           "714800",
			Lat:                  -84.387835,
			Long:                 33.748772,
			MainStreet:           "Default Street",
			CrossStreet:          "Hackathon Ave",
			CrossStreetTwo:       "One Live Boulevard",
			SpaceCount:           "100",
			MeterType:            "MSM",
			RateName:             "Business",
			EnforcementType:      "Pay by plate",
			HourlyRate:           "$2.00",
			MaxDurationInMinutes: "180",
			MinimumAmount:        "30",
			IncrementsInMinutes:  "30",
			ZoneGroupID:          3,
		},
		{
			Name:                 "Location 16",
			PMZoneCode:           "714057",
			Lat:                  -84.388002,
			Long:                 33.748999,
			MainStreet:           "Parking Street",
			CrossStreet:          "Boring Ave",
			CrossStreetTwo:       "Maple Way",
			SpaceCount:           "100",
			MeterType:            "MSM",
			RateName:             "Business",
			EnforcementType:      "Pay by plate",
			HourlyRate:           "$2.00",
			MaxDurationInMinutes: "180",
			MinimumAmount:        "30",
			IncrementsInMinutes:  "30",
			ZoneGroupID:          3,
		},
		{
			Name:                 "Location 17",
			PMZoneCode:           "714058",
			Lat:                  -84.388122,
			Long:                 33.749167,
			MainStreet:           "Real Street",
			CrossStreet:          "Existing Ave",
			CrossStreetTwo:       "A Road Boulevard",
			SpaceCount:           "100",
			MeterType:            "MSM",
			RateName:             "Business",
			EnforcementType:      "Pay by plate",
			HourlyRate:           "$2.00",
			MaxDurationInMinutes: "180",
			MinimumAmount:        "30",
			IncrementsInMinutes:  "30",
			ZoneGroupID:          3,
		},
	}
}
